name: Build and Publish package

on: workflow_dispatch

jobs:
  telegram-bot-api:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt update && sudo apt-get install -y zip libssl-dev zlib1g-dev g++ gperf cmake

    - name: Clone repo, Configure and build
      run: |
        git clone --recursive https://github.com/tdlib/telegram-bot-api.git
        cd telegram-bot-api
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
        zip telegram-bot-api.zip telegram-bot-api

    - name: Set Release Info
      id: release
      run: |
        echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "TITLE=Build #${GITHUB_RUN_NUMBER} - $(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.TAG }}"
        prerelease: false
        title: "${{ env.TITLE }}"
        files: |
          telegram-bot-api/build/telegram-bot-api
          telegram-bot-api/build/telegram-bot-api.zip
